language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: travis/installViaTravis.sh
script: travis/buildViaTravis.sh
cache:
  directories:
  - node_modules
